// <auto-generated />
using System;
using Danielson.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Danielson.Data.Migrations
{
    [DbContext(typeof(FormContext))]
    [Migration("20240510214104_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentConsiderations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComponentTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotObserved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QualitativeScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantitativeScore")
                        .HasColumnType("int");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTemplateId");

                    b.HasIndex("DomainId");

                    b.ToTable("ComponentAnswer", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentOptionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CombineWithPrevious")
                        .HasColumnType("bit");

                    b.Property<int?>("ComponentTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualitativeScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantitativeScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("ComponentOptionTemplate", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentConsiderations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SectionTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomainTemplateId");

                    b.ToTable("ComponentTemplate", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Domain", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.DomainTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomainType")
                        .HasColumnType("int");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int?>("FormTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("DomainTemplate", "danielson");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DomainDescription = "",
                            DomainTitle = "Default 1",
                            DomainType = 0,
                            IsActive = true,
                            IsDefault = true,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(432)
                        },
                        new
                        {
                            Id = -2,
                            DomainDescription = "",
                            DomainTitle = "Default 2",
                            DomainType = 1,
                            IsActive = true,
                            IsDefault = true,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(581)
                        },
                        new
                        {
                            Id = -3,
                            DomainDescription = "",
                            DomainTitle = "Default 3",
                            DomainType = 2,
                            IsActive = true,
                            IsDefault = true,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(593)
                        },
                        new
                        {
                            Id = -4,
                            DomainDescription = "",
                            DomainTitle = "Default 4",
                            DomainType = 3,
                            IsActive = true,
                            IsDefault = true,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(601)
                        });
                });

            modelBuilder.Entity("Danielson.Data.DataModels.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FinalScore")
                        .HasColumnType("float");

                    b.Property<string>("FinalSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMidterm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("SemesterDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentEvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Form", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.FormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormTemplate", "danielson");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", "danielson");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "admin@illinois.edu",
                            Guid = new Guid("be31303e-404a-471c-b7c0-dfdea01a4121"),
                            IsActive = false,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(1063),
                            Role = 99,
                            StudentId = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = -2,
                            Email = "student@illinois.edu",
                            Guid = new Guid("3784cb3c-681f-45b0-9b67-391ca17f5c0f"),
                            IsActive = false,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(1150),
                            Role = 1,
                            StudentId = 0,
                            Username = "student"
                        },
                        new
                        {
                            Id = -3,
                            Email = "supervisor@illinois.edu",
                            Guid = new Guid("50924bd6-1494-4c5c-a064-81b8aabedfa2"),
                            IsActive = false,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(1167),
                            Role = 2,
                            StudentId = 0,
                            Username = "supervisor"
                        },
                        new
                        {
                            Id = -4,
                            Email = "cotestaff@illinois.edu",
                            Guid = new Guid("b1dfc3d3-b726-4946-a65f-9489d360662f"),
                            IsActive = false,
                            LastUpdated = new DateTime(2024, 5, 10, 16, 41, 3, 780, DateTimeKind.Local).AddTicks(1198),
                            Role = 4,
                            StudentId = 0,
                            Username = "cotestaff"
                        });
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentAnswer", b =>
                {
                    b.HasOne("Danielson.Data.DataModels.ComponentTemplate", "ComponentTemplate")
                        .WithMany()
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Danielson.Data.DataModels.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentTemplate");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentOptionTemplate", b =>
                {
                    b.HasOne("Danielson.Data.DataModels.ComponentTemplate", "ComponentTemplate")
                        .WithMany("ComponentOptionTemplates")
                        .HasForeignKey("ComponentTemplateId");

                    b.Navigation("ComponentTemplate");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentTemplate", b =>
                {
                    b.HasOne("Danielson.Data.DataModels.DomainTemplate", "DomainTemplate")
                        .WithMany("ComponentTemplates")
                        .HasForeignKey("DomainTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainTemplate");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.Domain", b =>
                {
                    b.HasOne("Danielson.Data.DataModels.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.DomainTemplate", b =>
                {
                    b.HasOne("Danielson.Data.DataModels.Form", null)
                        .WithMany("CustomDomainTemplates")
                        .HasForeignKey("FormId");

                    b.HasOne("Danielson.Data.DataModels.FormTemplate", "FormTemplate")
                        .WithMany("CustomDomainTemplates")
                        .HasForeignKey("FormTemplateId");

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.ComponentTemplate", b =>
                {
                    b.Navigation("ComponentOptionTemplates");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.DomainTemplate", b =>
                {
                    b.Navigation("ComponentTemplates");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.Form", b =>
                {
                    b.Navigation("CustomDomainTemplates");
                });

            modelBuilder.Entity("Danielson.Data.DataModels.FormTemplate", b =>
                {
                    b.Navigation("CustomDomainTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
